# Generated by Django 6.0.6 on 2026-06-16 07:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AarthikBarsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aarthik_barsa",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Aarthik Barsa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aarthik Barsa",
                "verbose_name_plural": "Aarthik Barsa",
                "db_table": "aarthik_barsa",
                "ordering": ["aarthik_barsa"],
            },
        ),
        migrations.CreateModel(
            name="biwahaDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Chalani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chalani_no", models.PositiveIntegerField(unique=True)),
                ("chalani_date", models.CharField(max_length=20)),
                ("letter_type", models.CharField(max_length=255)),
                ("receiving_branch", models.CharField(max_length=255)),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_address", models.TextField()),
                ("subject", models.TextField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="chalani/"),
                ),
                ("bodartha", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-chalani_no"],
            },
        ),
        migrations.CreateModel(
            name="file_prakar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_prakar", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="fileBhitra",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_bhitra", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="JanmaDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="karmachari",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ward", models.CharField(max_length=255)),
                ("prakar", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("padh", models.CharField(max_length=20)),
                ("samparka", models.IntegerField()),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="KothaNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kotha_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kotha No."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kotha Number",
                "verbose_name_plural": "Kotha Numbers",
                "db_table": "kotha_number",
                "ordering": ["kotha_no"],
            },
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="migration_suchana",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("applicants_name", models.CharField(max_length=255)),
                ("application_date", models.DateField()),
                ("citizen_no", models.CharField(max_length=255)),
                ("current_ward", models.IntegerField(max_length=20)),
                ("verified", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="mrituDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="patraKoKisim",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patra_ko_kisim", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="rayak_khand_no",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rayak_khand_no", models.IntegerField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="sadasya_thapnuhos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sadasya", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="sakha_thapnuhos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sakha", models.CharField(max_length=255)),
                ("karya", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="woda",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("woda_name", models.CharField(max_length=255)),
                ("woda_no", models.IntegerField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("karya", models.CharField(max_length=255)),
                ("nagarpalika", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("citizen", "Citizen"),
                        ],
                        default="citizen",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="file_record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("record_code", models.CharField(max_length=255)),
                ("arthik_barsa", models.DateTimeField()),
                ("raik_khand", models.CharField(max_length=255)),
                ("raik_number", models.CharField(max_length=255)),
                ("kotha_no", models.CharField(max_length=255)),
                ("pariyojana", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("action", models.CharField(max_length=50)),
                (
                    "file_prakar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.file_prakar",
                    ),
                ),
                (
                    "file_bhitra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.filebhitra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="file_chalani",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("chalani_bujhiline", models.CharField(max_length=255)),
                ("chalani_date", models.DateTimeField()),
                ("chalani_firta_miti", models.DateTimeField()),
                ("chalani_status", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
                (
                    "file_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.file_record",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MahilaIdentityCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("municipality", models.CharField(max_length=100)),
                ("ward_no", models.PositiveIntegerField()),
                ("tole", models.CharField(max_length=255)),
                ("father_first_name", models.CharField(max_length=100)),
                ("father_middle_name", models.CharField(blank=True, max_length=100)),
                ("father_last_name", models.CharField(max_length=100)),
                ("mother_first_name", models.CharField(max_length=100)),
                ("mother_middle_name", models.CharField(blank=True, max_length=100)),
                ("mother_last_name", models.CharField(max_length=100)),
                ("grandfather_first_name", models.CharField(max_length=100)),
                (
                    "grandfather_middle_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("grandfather_last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mobile_no", models.CharField(max_length=20)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("widow", "Widow"),
                            ("divorced", "Divorced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "citizenship_document",
                    models.FileField(upload_to="mahila/documents/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.maincategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Darta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("darta_number", models.PositiveIntegerField(unique=True)),
                ("darta_date", models.DateField()),
                ("khata_number", models.CharField(blank=True, max_length=100)),
                ("pathaune", models.CharField(blank=True, max_length=255)),
                ("current_area_branch", models.CharField(blank=True, max_length=255)),
                (
                    "current_branch_members",
                    models.CharField(blank=True, max_length=255),
                ),
                ("kaifiyat", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "upload",
                    models.FileField(blank=True, null=True, upload_to="darta/uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dartas",
                        to="base.maincategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalbalikaIdentityCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("municipality", models.CharField(max_length=100)),
                ("ward_no", models.PositiveIntegerField()),
                ("tole", models.CharField(max_length=255)),
                ("father_first_name", models.CharField(max_length=100)),
                ("father_middle_name", models.CharField(blank=True, max_length=100)),
                ("father_last_name", models.CharField(max_length=100)),
                ("mother_first_name", models.CharField(max_length=100)),
                ("mother_middle_name", models.CharField(blank=True, max_length=100)),
                ("mother_last_name", models.CharField(max_length=100)),
                ("grandfather_first_name", models.CharField(max_length=100)),
                (
                    "grandfather_middle_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("grandfather_last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "birth_registration",
                    models.FileField(upload_to="balbalika/documents/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.maincategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApangaIdentityCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("municipality", models.CharField(max_length=100)),
                ("ward_no", models.PositiveIntegerField()),
                ("tole", models.CharField(max_length=255)),
                ("father_first_name", models.CharField(max_length=100)),
                ("father_middle_name", models.CharField(blank=True, max_length=100)),
                ("father_last_name", models.CharField(max_length=100)),
                ("mother_first_name", models.CharField(max_length=100)),
                ("mother_middle_name", models.CharField(blank=True, max_length=100)),
                ("mother_last_name", models.CharField(max_length=100)),
                ("grandfather_first_name", models.CharField(max_length=100)),
                (
                    "grandfather_middle_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("grandfather_last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("citizenship_no", models.CharField(max_length=100, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mobile_no", models.CharField(max_length=20)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("disability_type", models.CharField(max_length=100)),
                ("disability_nature", models.CharField(max_length=100)),
                ("disability_severity", models.CharField(max_length=100)),
                (
                    "citizenship_document",
                    models.FileField(upload_to="apanga/documents/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.maincategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="base.maincategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RayakNo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rayak_no", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rayak_nos",
                        to="base.maincategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rayak_nos",
                        to="base.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rayak No",
                "verbose_name_plural": "Rayak Nos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pariyojana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_code", models.CharField(max_length=100, unique=True)),
                ("project_date", models.DateField()),
                ("project_start_date", models.DateField(blank=True, null=True)),
                ("project_end_date", models.DateField(blank=True, null=True)),
                ("project_description", models.TextField(blank=True)),
                (
                    "project_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("project_location", models.CharField(blank=True, max_length=255)),
                ("project_manager", models.CharField(blank=True, max_length=255)),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "project_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="pariyojana/documents/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pariyojanas",
                        to="base.maincategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pariyojanas",
                        to="base.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="pratinidhi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("padh", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=20)),
                ("dateOfBirth", models.DateField()),
                ("contact_no", models.CharField(max_length=20)),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("rastriya_parichaya_patra", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
                (
                    "woda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.woda"
                    ),
                ),
            ],
        ),
    ]
