# Generated by Django 5.2.8 on 2026-06-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_seed_parichaya_patra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ApangaIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('tole', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('grandfather_first_name', models.CharField(max_length=100)),
                ('grandfather_middle_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='identity_cards/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizenship_no', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('mobile_no', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('disability_type', models.CharField(max_length=100)),
                ('disability_nature', models.CharField(max_length=100)),
                ('disability_severity', models.CharField(max_length=100)),
                ('citizenship_document', models.FileField(upload_to='apanga/documents/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalbalikaIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('tole', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('grandfather_first_name', models.CharField(max_length=100)),
                ('grandfather_middle_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='identity_cards/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birth_registration', models.FileField(upload_to='balbalika/documents/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MahilaIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('tole', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('grandfather_first_name', models.CharField(max_length=100)),
                ('grandfather_middle_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='identity_cards/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_no', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow'), ('divorced', 'Divorced')], max_length=20)),
                ('citizenship_document', models.FileField(upload_to='mahila/documents/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
