# Generated by Django 5.2.8 on 2026-06-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_maincategory_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apangaidentitycard',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='mahilaidentitycard',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='balbalikaidentitycard',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='apangaidentitycard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maincategory'),
        ),
        migrations.AddField(
            model_name='balbalikaidentitycard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maincategory'),
        ),
        migrations.AddField(
            model_name='mahilaidentitycard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maincategory'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
