<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-06-10 08:19
=======
# Generated by Django 5.1.6 on 2026-06-11 05:41
>>>>>>> origin/asmita

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("base", "0004_remove_apangaidentitycard_subcategory_and_more"),
=======
        ('base', '0004_remove_apangaidentitycard_subcategory_and_more'),
>>>>>>> origin/asmita
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="base.maincategory",
                    ),
                ),
=======
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.maincategory')),
>>>>>>> origin/asmita
            ],
        ),
    ]
