# Generated by Django 6.0.6 on 2026-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="JanmaDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
