# Generated by Django 5.2.8 on 2026-06-11 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aapangataparichayapatra_apangbhattaparichayapatra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApangaIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('tole', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('grandfather_first_name', models.CharField(max_length=100)),
                ('grandfather_middle_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='identity_cards/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizenship_no', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('mobile_no', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('disability_type', models.CharField(max_length=100)),
                ('disability_nature', models.CharField(max_length=100)),
                ('disability_severity', models.CharField(max_length=100)),
                ('citizenship_document', models.FileField(upload_to='apanga/documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalbalikaIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('tole', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('grandfather_first_name', models.CharField(max_length=100)),
                ('grandfather_middle_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='identity_cards/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birth_registration', models.FileField(upload_to='balbalika/documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MahilaIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('tole', models.CharField(max_length=255)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('grandfather_first_name', models.CharField(max_length=100)),
                ('grandfather_middle_name', models.CharField(blank=True, max_length=100)),
                ('grandfather_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='identity_cards/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_no', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow'), ('divorced', 'Divorced')], max_length=20)),
                ('citizenship_document', models.FileField(upload_to='mahila/documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.maincategory')),
            ],
        ),
        migrations.DeleteModel(
            name='AapangataParichayaPatra',
        ),
        migrations.DeleteModel(
            name='ApangBhattaParichayaPatra',
        ),
        migrations.DeleteModel(
            name='BalabalikaParichayaPatra',
        ),
        migrations.DeleteModel(
            name='MahilaParichayaPatra',
        ),
        migrations.AddField(
            model_name='mahilaidentitycard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maincategory'),
        ),
        migrations.AddField(
            model_name='balbalikaidentitycard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maincategory'),
        ),
        migrations.AddField(
            model_name='apangaidentitycard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maincategory'),
        ),
    ]
