# Generated by Django 5.1.6 on 2026-06-11 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Letter Type',
                'verbose_name_plural': 'Letter Types',
            },
        ),
        migrations.CreateModel(
            name='Chalani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalani_no', models.PositiveIntegerField(unique=True)),
                ('chalani_date', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=255, verbose_name='पत्र पाउने कार्यालय वा व्यक्तिको नाम')),
                ('receiver_address', models.TextField(verbose_name='पत्र पाउने कार्यालय वा व्यक्तिको ठेगाना')),
                ('subject', models.TextField(verbose_name='बिषय')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chalani/')),
                ('bodartha', models.TextField(blank=True, null=True, verbose_name='बोदार्थ')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='कैफियत')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_chalanis', to='base.branch')),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chalanis', to='base.lettertype')),
            ],
            options={
                'ordering': ['-chalani_no'],
            },
        ),
    ]
