# Generated by Django 6.0.6 on 2026-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_branch_lettertype_chalani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalani',
            name='receiving_branch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='letter_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='bodartha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='receiver_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='receiver_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='subject',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='LetterType',
        ),
    ]
