# Generated by Django 5.2.8 on 2026-06-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_apangaidentitycard_balbalikaidentitycard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darta_number', models.PositiveIntegerField(unique=True)),
                ('darta_date', models.DateField()),
                ('khata_number', models.CharField(blank=True, max_length=100)),
                ('pathaune', models.CharField(blank=True, max_length=255)),
                ('current_area_branch', models.CharField(blank=True, max_length=255)),
                ('current_branch_members', models.CharField(blank=True, max_length=255)),
                ('kaifiyat', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='darta/uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dartas', to='base.maincategory')),
            ],
        ),
    ]
