# Generated by Django 6.0.6 on 2026-06-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_janmadarta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JanmaDarta",
        ),
    ]
