# Generated by Django 6.0.6 on 2026-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_chalani_receiving_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KothaNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kotha_no', models.CharField(max_length=100, unique=True, verbose_name='कोठा नं')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kotha Number',
                'verbose_name_plural': 'Kotha Numbers',
                'db_table': 'kotha_number',
                'ordering': ['kotha_no'],
            },
        ),
    ]
