# Generated by Django 6.0.6 on 2026-06-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_delete_janmadarta"),
    ]

    operations = [
        migrations.CreateModel(
            name="biwahaDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="file_prakar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_prakar", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="fileBhitra",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_bhitra", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="JanmaDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="migration_suchana",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("applicants_name", models.CharField(max_length=255)),
                ("application_date", models.DateField()),
                ("citizen_no", models.CharField(max_length=255)),
                ("current_ward", models.IntegerField(max_length=20)),
                ("verified", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="mrituDarta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("sifaris_prakar", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="rayak_khand_no",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rayak_khand_no", models.IntegerField(max_length=255)),
                ("action", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="file_record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("record_code", models.CharField(max_length=255)),
                ("arthik_barsa", models.DateTimeField()),
                ("raik_khand", models.CharField(max_length=255)),
                ("raik_number", models.CharField(max_length=255)),
                ("kotha_no", models.CharField(max_length=255)),
                ("pariyojana", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="identity_cards/photos/")),
                ("action", models.CharField(max_length=50)),
                (
                    "file_prakar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.file_prakar",
                    ),
                ),
                (
                    "file_bhitra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.filebhitra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="file_chalani",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("chalani_bujhiline", models.CharField(max_length=255)),
                ("chalani_date", models.DateTimeField()),
                ("chalani_firta_miti", models.DateTimeField()),
                ("chalani_status", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
                (
                    "file_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.file_record",
                    ),
                ),
            ],
        ),
    ]
