# Generated by Django 5.2.8 on 2026-06-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_darta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pariyojana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=100, unique=True)),
                ('project_date', models.DateField()),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True)),
                ('project_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('project_manager', models.CharField(blank=True, max_length=255)),
                ('project_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('project_documents', models.FileField(blank=True, null=True, upload_to='pariyojana/documents/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pariyojanas', to='base.maincategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pariyojanas', to='base.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
