# Generated by Django 5.2.8 on 2026-06-11 06:38

from django.db import migrations


def seed_digital_file_categories(apps, schema_editor):
    MainCategory = apps.get_model("base", "MainCategory")
    SubCategory = apps.get_model("base", "SubCategory")

    # Create or get the main category
    digital_file, created = MainCategory.objects.get_or_create(
        name="Digital File Pranali",
        defaults={"name": "Digital File Pranali"}
    )

    # Create subcategories
    subcategories = [
        "Pariyojana",
        "Kaaryakram",
        "Budget",
        "Plan",
    ]

    for subcat_name in subcategories:
        SubCategory.objects.get_or_create(
            main_category=digital_file,
            name=subcat_name,
            defaults={"name": subcat_name}
        )


def unseed_digital_file_categories(apps, schema_editor):
    MainCategory = apps.get_model("base", "MainCategory")
    MainCategory.objects.filter(name="Digital File Pranali").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pariyojana'),
    ]

    operations = [
        migrations.RunPython(seed_digital_file_categories, unseed_digital_file_categories),
    ]
