# Generated by Django 6.0.6 on 2026-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_kothanumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AarthikBarsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aarthik_barsa', models.CharField(max_length=100, unique=True, verbose_name='Aarthik Barsa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aarthik Barsa',
                'verbose_name_plural': 'Aarthik Barsa',
                'db_table': 'aarthik_barsa',
                'ordering': ['aarthik_barsa'],
            },
        ),
        migrations.AlterField(
            model_name='kothanumber',
            name='kotha_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kotha No.'),
        ),
    ]
