# Generated by Django 5.2.8 on 2026-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_devicetoken_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration_suchana',
            name='current_ward',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rayak_khand_no',
            name='rayak_khand_no',
            field=models.IntegerField(),
        ),
    ]
